// export const BASE_URL = "http://localhost:3008";
export const BASE_URL = "https://playlist-ykrantz.herokuapp.com";
export const TITLE_LENGTH = 35;
export const PLAYLIST_NAME_MAX_LENGTH = 15;

export const initSearchApiResults = [
  {
    type: "video",
    title:
      "Best Songs Ever : Alan Walker, Bruno Mars, OneRepublic, Katy Perry, Sia, Taylor Swift, Rihanna",
    id: "MR4PVyEZ_Kk",
    url: "https://www.youtube.com/watch?v=MR4PVyEZ_Kk",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/MR4PVyEZ_Kk/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDOWqx7y73gOSdIiygtXz3oNbYotg",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/MR4PVyEZ_Kk/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDOWqx7y73gOSdIiygtXz3oNbYotg",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Happy Songs Playlist",
      channelID: "UC1TkVT51Tv4f05LUtQCHnUw",
      url: "https://www.youtube.com/channel/UC1TkVT51Tv4f05LUtQCHnUw",
      bestAvatar: {
        url: "https://yt3.ggpht.com/qa47smrqfhOVbgMmLtze3iZePKS3eEv2HsXg5WrfmMGKFp-xF1h1jUb5xieaBgDhud2zMyqt=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/qa47smrqfhOVbgMmLtze3iZePKS3eEv2HsXg5WrfmMGKFp-xF1h1jUb5xieaBgDhud2zMyqt=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: ["Verified"],
      verified: true,
    },
    description: null,
    views: 243575,
    duration: "2:02:36",
    uploadedAt: "5 months ago",
  },
  {
    type: "video",
    title: "One Direction - Best Song Ever",
    id: "o_v9MY_FMcw",
    url: "https://www.youtube.com/watch?v=o_v9MY_FMcw",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/o_v9MY_FMcw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD-haT9h7TPy4cgAVdYuuF4KPopkg",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/o_v9MY_FMcw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD-haT9h7TPy4cgAVdYuuF4KPopkg",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/o_v9MY_FMcw/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLARo1I5vMgjoWYmxA7LIIq-ebUBYw",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "One Direction",
      channelID: "UCb2HGwORFBo94DmRx4oLzow",
      url: "https://www.youtube.com/channel/UCb2HGwORFBo94DmRx4oLzow",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLTofIUUHLf2BmQX3QxApZwNdlvzrOYZfHnGZ0_eliw=s88-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLTofIUUHLf2BmQX3QxApZwNdlvzrOYZfHnGZ0_eliw=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: ["Official Artist Channel"],
      verified: true,
    },
    description: null,
    views: 762464473,
    duration: "6:13",
    uploadedAt: "8 years ago",
  },
  {
    type: "video",
    title:
      "TOP 40 Songs of 2021 2022 \\ Best English Songs  (Best Hit Music Playlist) on Spotify  @Sky Music PE",
    id: "3jgH5weXYwA",
    url: "https://www.youtube.com/watch?v=3jgH5weXYwA",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/3jgH5weXYwA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKQSnMTnjcjDVNEh1qEdIGMnA31g",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/3jgH5weXYwA/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKQSnMTnjcjDVNEh1qEdIGMnA31g",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/3jgH5weXYwA/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAkjoaK4You85GX8tHKO9uZWuBOow",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Sky Music PE",
      channelID: "UCcsrHJDzOxM7foZQWiBr8qQ",
      url: "https://www.youtube.com/channel/UCcsrHJDzOxM7foZQWiBr8qQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLRIw65ov7RZ9lUeLKAfkIiWg39sKblse_TzzvmI=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLRIw65ov7RZ9lUeLKAfkIiWg39sKblse_TzzvmI=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 17256410,
    duration: "3:12:27",
    uploadedAt: "7 months ago",
  },
  {
    type: "video",
    title:
      "CCR Greatest Hits Full Album - The Best of CCR - CCR Love Songs Ever (HQ)",
    id: "h2tzGE7yZok",
    url: "https://www.youtube.com/watch?v=h2tzGE7yZok",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/h2tzGE7yZok/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAo9xcXoFPADoYJ-6beXJ0Z3TXf0g",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/h2tzGE7yZok/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAo9xcXoFPADoYJ-6beXJ0Z3TXf0g",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/h2tzGE7yZok/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCILDtbTxv9WjncNTLuXnY8h6X78g",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Classic Rock",
      channelID: "UCPHMQTd8_ocg9LXBhs2t7_A",
      url: "https://www.youtube.com/channel/UCPHMQTd8_ocg9LXBhs2t7_A",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLTxtv_VZZlzb9YKZyPA88H8Jbh3k5hhcC-QLBWT=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLTxtv_VZZlzb9YKZyPA88H8Jbh3k5hhcC-QLBWT=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 646743,
    duration: "1:18:36",
    uploadedAt: "1 year ago",
  },
  {
    type: "video",
    title: "70s 80s 90s Classic Rock | Best Classic Rock Songs Of All Time",
    id: "ODftu0T1Nxs",
    url: "https://www.youtube.com/watch?v=ODftu0T1Nxs",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/ODftu0T1Nxs/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCzZmQknuRPPkveWPZpaMEY7MLOng",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/ODftu0T1Nxs/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCzZmQknuRPPkveWPZpaMEY7MLOng",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Classic Rock Music",
      channelID: "UCz4V_czcGngq3dC39UjDfbQ",
      url: "https://www.youtube.com/channel/UCz4V_czcGngq3dC39UjDfbQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLRjyBjlpvDTv1pedhw1hQbPRvndAsu0cjbeNvKM=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLRjyBjlpvDTv1pedhw1hQbPRvndAsu0cjbeNvKM=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 462036,
    duration: "1:45:41",
    uploadedAt: "5 months ago",
  },
  {
    type: "video",
    title:
      "Best Oldies Songs Of 1980s - 80s 90s Greatest Hits - The Best Oldies Song Ever",
    id: "e_Z1CawQIvo",
    url: "https://www.youtube.com/watch?v=e_Z1CawQIvo",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/e_Z1CawQIvo/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLApAgJeSQ2ySuwoiGxWM8ot0XgIjg",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/e_Z1CawQIvo/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLApAgJeSQ2ySuwoiGxWM8ot0XgIjg",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Oldies Music",
      channelID: "UCBx8oobBZc72tOFOMAEzthA",
      url: "https://www.youtube.com/user/torrentgames16",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLRn3bYjoT2UliDJKCiDHl6LWm9zFciySTmGCuFwog=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLRn3bYjoT2UliDJKCiDHl6LWm9zFciySTmGCuFwog=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 2137729,
    duration: "2:03:19",
    uploadedAt: "1 year ago",
  },
  {
    type: "video",
    title:
      "Best Music 2000 to 2020 - New & Old Songs (Top Throwback Songs 2000 & New Music 2020)",
    id: "ZWnHbSfmn6Y",
    url: "https://www.youtube.com/watch?v=ZWnHbSfmn6Y",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/ZWnHbSfmn6Y/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDNFv-VYyuIrmgsLWEIbkhdKh4DMw",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/ZWnHbSfmn6Y/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDNFv-VYyuIrmgsLWEIbkhdKh4DMw",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/ZWnHbSfmn6Y/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDJ3RW6JScOPfz6jFkIWIMKJElD8w",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "2000S HITS",
      channelID: "UCr_6k9YCqcx6vmj-YZe33uQ",
      url: "https://www.youtube.com/channel/UCr_6k9YCqcx6vmj-YZe33uQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/Tc66q3rZffofggtWw55Rd7MqvblxmTs20m5J4poTWWDQQy1P5GDk-p0vljw-dfgPe8WpqxNu=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/Tc66q3rZffofggtWw55Rd7MqvblxmTs20m5J4poTWWDQQy1P5GDk-p0vljw-dfgPe8WpqxNu=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 2520466,
    duration: "1:00:28",
    uploadedAt: "1 year ago",
  },
  {
    type: "video",
    title: "Best throwback songs ever (Part 1)",
    id: "wSUDODrYw5U",
    url: "https://www.youtube.com/watch?v=wSUDODrYw5U",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/wSUDODrYw5U/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCFqPLtWkHTFw_hc5_woOD8ZKmTzg",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/wSUDODrYw5U/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCFqPLtWkHTFw_hc5_woOD8ZKmTzg",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Just Chillin'",
      channelID: "UC5n1DU9HpHD3dbiP6cio0cw",
      url: "https://www.youtube.com/channel/UC5n1DU9HpHD3dbiP6cio0cw",
      bestAvatar: {
        url: "https://yt3.ggpht.com/SM3EsQcMod8XTiOQnsVeWan28MzIR7T22MFAVlZCWvtJPqqQb9bYa2_I4RfbGt2YFXTzmiFU=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/SM3EsQcMod8XTiOQnsVeWan28MzIR7T22MFAVlZCWvtJPqqQb9bYa2_I4RfbGt2YFXTzmiFU=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 2491057,
    duration: "57:22",
    uploadedAt: "5 months ago",
  },
  {
    type: "video",
    title: "NOW 100 HITS I THE LEGENDS I THE BEST OF MUSIC ALBUM",
    id: "e6vVGdeweX4",
    url: "https://www.youtube.com/watch?v=e6vVGdeweX4",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/e6vVGdeweX4/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLD5rGHkkfKRJF72YWNhit79oysaaA",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/e6vVGdeweX4/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLD5rGHkkfKRJF72YWNhit79oysaaA",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "SCHLAGER AKTUELL",
      channelID: "UCOVD3PtbJGiAcp-c6opijoQ",
      url: "https://www.youtube.com/channel/UCOVD3PtbJGiAcp-c6opijoQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLQqSBYCbxdc4lxir4ufqgz2h_6b3_iaelGdd1On=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLQqSBYCbxdc4lxir4ufqgz2h_6b3_iaelGdd1On=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 2986615,
    duration: "5:27:40",
    uploadedAt: "1 year ago",
  },
  {
    type: "video",
    title: "Top 100 Best Songs Of All Time",
    id: "zSmjW5fNUZA",
    url: "https://www.youtube.com/watch?v=zSmjW5fNUZA",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/zSmjW5fNUZA/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDpBBZq9FTG9i_0zdhDm2so0w97EQ",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/zSmjW5fNUZA/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDpBBZq9FTG9i_0zdhDm2so0w97EQ",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Top Music Channel",
      channelID: "UCqmHXdMF817v4_1xreTw6sQ",
      url: "https://www.youtube.com/channel/UCqmHXdMF817v4_1xreTw6sQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLTDwrqmnDcv-l8HL0zou0BmGiIURwN3R-JxfCX2=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLTDwrqmnDcv-l8HL0zou0BmGiIURwN3R-JxfCX2=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 28349567,
    duration: "17:53",
    uploadedAt: "5 years ago",
  },
  {
    type: "video",
    title: "Top 100 Greatest Songs of All Time",
    id: "1vNieQb8MBw",
    url: "https://www.youtube.com/watch?v=1vNieQb8MBw",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/1vNieQb8MBw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCNGl61y0Tx0fqD5O8wcdttMvGx7Q",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/1vNieQb8MBw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCNGl61y0Tx0fqD5O8wcdttMvGx7Q",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/1vNieQb8MBw/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBs9JN3Nwb-PIUVDTKk4pvMGZOmOw",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "ZtarOZ - Songs",
      channelID: "UCMDaXlbsuhn0GuYeKkfwIkQ",
      url: "https://www.youtube.com/channel/UCMDaXlbsuhn0GuYeKkfwIkQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/3eGOqJJ5ZLCiSTfcztm92ohvoNQ3IpNg1bnjpeo1OUN1wRJ1CuiubE8WWKHfoMiLAQv0VcD-AA=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/3eGOqJJ5ZLCiSTfcztm92ohvoNQ3IpNg1bnjpeo1OUN1wRJ1CuiubE8WWKHfoMiLAQv0VcD-AA=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 1333123,
    duration: "10:56",
    uploadedAt: "10 months ago",
  },
  {
    type: "video",
    title:
      "Best Golden Oldies Songs Of All Time - Golden Oldies Collection - Oldies But Goodies Best Hits",
    id: "_CZw8pmEcis",
    url: "https://www.youtube.com/watch?v=_CZw8pmEcis",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/_CZw8pmEcis/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLALrbfts1HP1cfX3MfDcREfELbMXA",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/_CZw8pmEcis/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLALrbfts1HP1cfX3MfDcREfELbMXA",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: ["New"],
    author: {
      name: "Oldies Classic Music Box",
      channelID: "UC_7GPhVZ2BquP6hPhjK_XFg",
      url: "https://www.youtube.com/channel/UC_7GPhVZ2BquP6hPhjK_XFg",
      bestAvatar: {
        url: "https://yt3.ggpht.com/HayESJY6wm1nScS2J5wueHaCFHpbb-l324VWIziCD3gaCF2OSf3Gp4sVhS_JhPZBDE4bmF1ZtA=s88-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/HayESJY6wm1nScS2J5wueHaCFHpbb-l324VWIziCD3gaCF2OSf3Gp4sVhS_JhPZBDE4bmF1ZtA=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: ["Official Artist Channel"],
      verified: true,
    },
    description: null,
    views: 2720,
    duration: "1:39:29",
    uploadedAt: "2 hours ago",
  },
  {
    type: "video",
    title: "Top Hits 100 - Top 40 Popular Songs (Music Hot This Week)",
    id: "PuJQhtg1VCM",
    url: "https://www.youtube.com/watch?v=PuJQhtg1VCM",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/PuJQhtg1VCM/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBShZoovm3mazB3l1V-hvUBRznQmw",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/PuJQhtg1VCM/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBShZoovm3mazB3l1V-hvUBRznQmw",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/PuJQhtg1VCM/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCrwUvY7Hpli1JUhj5m_HeYg0UQlw",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "DMnet Music",
      channelID: "UCD741Gk4lh8M0Agf5FUpJfg",
      url: "https://www.youtube.com/channel/UCD741Gk4lh8M0Agf5FUpJfg",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLTnDmBBcvhEBmVxo50DhWm6szTWHiixtT5LZCqFoQ=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLTnDmBBcvhEBmVxo50DhWm6szTWHiixtT5LZCqFoQ=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 23257821,
    duration: "2:11:02",
    uploadedAt: "3 years ago",
  },
  {
    type: "video",
    title: "Top 40 Popular Songs - Top Song This Week (Vevo Hot This Week)",
    id: "fSqicTTg1Ps",
    url: "https://www.youtube.com/watch?v=fSqicTTg1Ps",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/fSqicTTg1Ps/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCqh6U0Dc34-qno3qx71CcQGy3bwQ",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/fSqicTTg1Ps/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCqh6U0Dc34-qno3qx71CcQGy3bwQ",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/fSqicTTg1Ps/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA8eJOaNJiaHOUZ6_NcpPimOgVtxg",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Playlist US-UK Music - CEP",
      channelID: "UCJF5gGOftRW5YnGv5Qg0Qvg",
      url: "https://www.youtube.com/channel/UCJF5gGOftRW5YnGv5Qg0Qvg",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLRQVjKD2RKRktvLIVwrzxQg4yGhOgEoXdKxuo5Y=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLRQVjKD2RKRktvLIVwrzxQg4yGhOgEoXdKxuo5Y=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 12645722,
    duration: "2:11:02",
    uploadedAt: "3 years ago",
  },
  {
    type: "video",
    title: "Top 25 greatest songs ever",
    id: "n8VKYnDf40Y",
    url: "https://www.youtube.com/watch?v=n8VKYnDf40Y",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/n8VKYnDf40Y/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDRT593So-wEqyhRxP769LK398eUw",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/n8VKYnDf40Y/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDRT593So-wEqyhRxP769LK398eUw",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "0707NicePlayer",
      channelID: "UCr99Q3S9zadPAcyE_OeLozQ",
      url: "https://www.youtube.com/user/0707NicePlayer",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLS3TPstKLOnlLFtg9Vr9y8eyCbpMtQ-oJN-Gg=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLS3TPstKLOnlLFtg9Vr9y8eyCbpMtQ-oJN-Gg=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 9860566,
    duration: "8:32",
    uploadedAt: "12 years ago",
  },
  {
    type: "video",
    title: "Tenacious D - Tribute (Official Video)",
    id: "_lK4cX5xGiQ",
    url: "https://www.youtube.com/watch?v=_lK4cX5xGiQ",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/_lK4cX5xGiQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBZjfj454Q72KQTLpQsv5Z99XvOZQ",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/_lK4cX5xGiQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBZjfj454Q72KQTLpQsv5Z99XvOZQ",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/_lK4cX5xGiQ/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBVeeDrzbw097L5N_WphREduOy3VA",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Tenacious D",
      channelID: "UCH-Uobgd_TrFNnxuphSnbeQ",
      url: "https://www.youtube.com/channel/UCH-Uobgd_TrFNnxuphSnbeQ",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLQ3JNnE3LDC5pBIUaRLmUQEU-yJrNY6y_sR9MtfNw=s88-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLQ3JNnE3LDC5pBIUaRLmUQEU-yJrNY6y_sR9MtfNw=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: ["Official Artist Channel"],
      verified: true,
    },
    description: null,
    views: 111436523,
    duration: "4:53",
    uploadedAt: "11 years ago",
  },
  {
    type: "video",
    title: "Top 100 Most Liked Songs of All Time (Mainstream)",
    id: "MEQH2yC7uKg",
    url: "https://www.youtube.com/watch?v=MEQH2yC7uKg",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/MEQH2yC7uKg/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAofXolKS3_Aloc7PFLFj6JbAJB2A",
      width: 720,
      height: 404,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/MEQH2yC7uKg/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAofXolKS3_Aloc7PFLFj6JbAJB2A",
        width: 720,
        height: 404,
      },
      {
        url: "https://i.ytimg.com/vi/MEQH2yC7uKg/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB4l1VdqGVSB0SY4vG2C1aQKjomXg",
        width: 360,
        height: 202,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "Redlist",
      channelID: "UCgR4pXCr9fGiUvZfsnlZ2Hg",
      url: "https://www.youtube.com/channel/UCgR4pXCr9fGiUvZfsnlZ2Hg",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLTUu5M0KQBX1813-824Zqir6qjX8_T8hjUbweye3A=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLTUu5M0KQBX1813-824Zqir6qjX8_T8hjUbweye3A=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: ["Verified"],
      verified: true,
    },
    description: null,
    views: 722606,
    duration: "12:05",
    uploadedAt: "8 months ago",
  },
  {
    type: "video",
    title: "Top 300 Most Liked Songs Of All Time (July 2021) REUPLOAD",
    id: "GlnsvCUbej0",
    url: "https://www.youtube.com/watch?v=GlnsvCUbej0",
    bestThumbnail: {
      url: "https://i.ytimg.com/vi/GlnsvCUbej0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAKYx6DU6Ke-D2PgMdO8Ik5Qfm2vg",
      width: 480,
      height: 270,
    },
    thumbnails: [
      {
        url: "https://i.ytimg.com/vi/GlnsvCUbej0/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAKYx6DU6Ke-D2PgMdO8Ik5Qfm2vg",
        width: 480,
        height: 270,
      },
    ],
    isUpcoming: false,
    upcoming: null,
    isLive: false,
    badges: [],
    author: {
      name: "AML Top Music List",
      channelID: "UCAtlQ1e-be3wlU6t8ZJMddw",
      url: "https://www.youtube.com/channel/UCAtlQ1e-be3wlU6t8ZJMddw",
      bestAvatar: {
        url: "https://yt3.ggpht.com/ytc/AKedOLSgN1XB6MPRUVyqgPiBEhIH7PiU8hk5_ubbllNp=s68-c-k-c0x00ffffff-no-rj",
        width: 68,
        height: 68,
      },
      avatars: [
        {
          url: "https://yt3.ggpht.com/ytc/AKedOLSgN1XB6MPRUVyqgPiBEhIH7PiU8hk5_ubbllNp=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
      ],
      ownerBadges: [],
      verified: false,
    },
    description: null,
    views: 899449,
    duration: "30:21",
    uploadedAt: "11 months ago",
  },
];
